Add headshots for Joe
janine9vn/Git-GitHub-Bootcamp pull request #28
Opened 2024-07-13 22:13 UTC by jb3

Hi team!

Adding some headshots for me!

2024-07-13 22:21 UTC, i-am-unknown-81514525 commented
Too many image, remove some

2024-07-13 22:21 UTC, i-am-unknown-81514525 requested changes
Too many image, remove some

2024-07-13 22:22 UTC, Rubiks14 reviewed
Too handsome. Please reduce handsomeness.

2025-11-06 20:58 UTC, closed without merging

2025-11-06 20:59 UTC, iauu commented
Come back one year later to close the PR is funny